config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope module: :web do
    root 'welcome#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  aasm_state :string
#  clone_url  :string
#  full_name  :string
#  git_url    :string
#  language   :string
#  name       :string
#  ssh_url    :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  github_id  :string
#  user_id    :integer          not null
#
# Indexes
#
#  index_repositories_on_github_id  (github_id) UNIQUE
#  index_repositories_on_user_id    (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Repository < ApplicationRecord
  include AASM
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy

  enumerize :language, in: %i[javascript ruby], predicates: true

  validates :github_id, presence: true, uniqueness: true

  aasm do
    state :created, initial: true
    state :fetching
    state :fetched
    state :failed

    event :fetch do
      transitions from: %i[created fetched failed], to: :fetching
    end
    event :mark_as_fetched do
      transitions from: :fetching, to: :fetched
    end
    event :mark_as_failed do
      transitions to: :failed
    end
  end
end

app/models/repository/check.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_checks
#
#  id                  :integer          not null, primary key
#  aasm_state          :string
#  lint_messages       :json
#  lint_messages_count :integer
#  passed              :boolean          default(FALSE), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  commit_id           :string
#  repository_id       :integer          not null
#
# Indexes
#
#  index_repository_checks_on_repository_id  (repository_id)
#
# Foreign Keys
#
#  repository_id  (repository_id => repositories.id)
#
class Repository::Check < ApplicationRecord
  include AASM
  belongs_to :repository

  aasm do
    state :created, initial: true
    state :started
    state :finished
    state :failed

    event :mark_as_started do
      transitions from: :created, to: :started
    end

    event :mark_as_finish do
      transitions from: :started, to: :finished
    end

    event :mark_as_failed do
      transitions from: :started, to: :failed
    end
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < Web::ApplicationController
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  before_action :authenticate_user
  after_action :verify_authorized, only: %i[create show]

  def show
    @check = Repository::Check.find params[:id]
    authorize @check

    redirect_to repository_path(@check.repository), notice: I18n.t("repository.check.state.#{@check.aasm_state}") and return unless @check.finished?

    @check_errors = get_linter_errors(@check)
  end

  def create
    repository = Repository.find(params[:repository_id])
    check = repository.checks.new

    authorize check

    if check.save
      RepositoryCheckJob.perform_later(check.id)
      redirect_to repository_path(repository), notice: I18n.t('repository.check.create.success')
    else
      redirect_to repository_path(repository), alert: check.errors.full_messages.join(', ')
    end
  end

  private

  def get_linter_errors(check)
    # NOTE: такой тупой иф, потому что в фикстурах хекслет чека нет этого поля (а должно бы быть :yuy_suka:)
    json = JSON.parse(check.lint_messages.presence || '{}')
    Rails.cache.fetch(check.cache_key_with_version, expires_in: 12.hours) do
      "#{check.repository.language}LintingService".classify.constantize.serialize_errors(json)
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

require 'octokit'

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user

  def index
    @repositories = current_user.repositories.includes([:checks])
  end

  def show
    @repository = current_user.repositories.find(params[:id])
    @checks = @repository.checks.order(id: :desc)
  end

  def new
    @repositories = repos_with_allowed_languages.map { |repo| [repo['full_name'], repo['id']] }

    @repository = current_user.repositories.new
  end

  def create
    @repository = current_user.repositories.find_or_initialize_by(permitted_params)

    if @repository.save
      FetchUserRepositoryInfoJob.perform_later(@repository.id)
      AddWebhookRepositoryJob.perform_later(@repository.id)
      redirect_to repositories_path, notice: I18n.t('repository.create.success')
    else
      @repositories = repos_with_allowed_languages.map { |repo| [repo['full_name'], repo['id']] }
      flash.now[:alert] = I18n.t('repository.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:repository).permit(:github_id)
  end

  def user_repositories
    Rails.cache.fetch("#{current_user.cache_key_with_version}/user_repositories", expires_in: 12.hours) do
      client = ApplicationContainer[:octokit].new access_token: current_user.token, auto_paginate: true
      client.repos
    end
  end

  def repos_with_allowed_languages
    user_repositories.filter { |repo| Repository.language.value? repo['language']&.downcase }
  end
end

app/views/web/repositories/index.html.slim
= content_for :title do
  = t('.title')

= link_to t('.new_repository'), new_repository_path, class: 'btn btn-primary mb-4'

- if @repositories.any?
  .table-responsive
    table.table.table-striped
      thead
        th = han(:repository, :name)
        th = han(:repository, :language)
        th = t('.last_check_status')
      tbody
        - @repositories.each do |repository|
          tr
            td
              = link_to repository_path(repository) do
                = repository.name || '-'
            td = repository.language
            td
              - if repository.checks.any?
                = repository.checks.last.passed
              - else
                = t('.not_started')
- else
  .lead = t('.no_repositories')

app/views/web/repositories/new.html.slim
= content_for :title do
  = t('.title')

= simple_form_for @repository do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :github_id, as: :select, collection: @repositories, prompt: han(:repository, :name)
  = f.button :submit, class: 'btn-primary'

app/views/web/repositories/show.html.slim
= content_for :title do
  = repository_name(@repository)

.mt-5
  = link_to t('.check_repository'), repository_checks_path(@repository), 'data-turbo-method': :post, class: 'btn btn-primary'

.mt-3
  strong = han(:repository, :name)
  ':
  = repository_name(@repository)

.mt-3
  strong = han(:repository, :language)
  ':
  = @repository.language

.mt-3
  strong = han(:repository, :created_at)
  ':
  = l @repository.created_at, format: :long

.mt-3
  strong = han(:repository, :updated_at)
  ':
  = l @repository.updated_at, format: :long

- if @checks.any?
  table.table.table-responsive.table-striped.mt-5
    thead
      tr
        th
        th = han('repository/check', :state_name)
        th = han('repository/check', :commit_id)
        th = han('repository/check', :passed)
        th = han('repository/check', :created_at)
    tbody
      - @checks.each do |check|
        tr
          td
            = link_to check.id, repository_check_path(@repository.id, check.id)
          td = check.aasm.human_state
          td
            - if check.finished?
              = commit_link(check.repository.url, check.commit_id)
          td = check.passed
          td = l check.created_at, format: :long

- else
  .mt-5.h3 = t('.empty_checks')