config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope module: :web do
    root 'welcome#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('application_name')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.svg'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

  body.min-vh-100.d-flex.flex-column
    header.flex-shrink-0
      nav.navbar.navbar-expand-md.navbar-dark.bg-dark
        .container-fluid
          = link_to root_path, class: 'navbar-brand d-flex align-items-center' do
            = t('application_name')

          button.navbar-toggler[type='button' data-bs-toggle='collapse' data-bs-target='#navbarScroll'
            aria-controls='navbarScroll' aria-expanded='false' aria-label=t('.toggle_navigation')]
            span.navbar-toggler-icon

          .collapse.navbar-collapse#navbarScroll
            ul.navbar-nav.mb-2.mb-md-0.w-100.justify-content-end
              - if signed_in?
                li.nav-item.me-auto
                  = link_to t('.repositories'), repositories_path, class: class_names('nav-link', active: current_page?(repositories_path))
                li.nav-item
                  a.nav-link.disabled.text-white-50 = current_user.email
                li.nav-item
                  = button_to t('.sign_out'), auth_logout_path, method: :delete, data: { turbo: false }, class: 'nav-link'

              - else
                li.nav-item
                  = button_to auth_request_path(:github), method: :post, data: { turbo: false }, class: 'nav-link' do
                    span.bi.bi-github.me-2
                    = t('.sign_in')

    main.flex-grow-1.flex-shrink-0
      .container-fluid
        = render_flash_messages dismissible: true

      .container.my-5
        - if content_for?(:title)
          h1.mb-4 = yield(:title)

        = yield

    footer.footer.py-3.flex-shrink-0.bg-dark.bg-opacity-75.text-white
      .container-fluid
        = t('.copyright', year: Time.current.year)